name: nightly-release

on:
  schedule:
    # 11:00 UTC is 03:00 in Pacific standard time (UTC-8), which is well
    # after nightly TensorFlow wheels are released (around 1--2 AM).
    # (cron syntax: minute hour day-of-month month day-of-week)
    - cron: '0 11 * * *'

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  nightly-release:
    runs-on: ubuntu-22.04
    needs: ci
    if: github.repository == 'tensorflow/tensorboard'
    steps:
      - name: Download pip package
        uses: actions/download-artifact@v3
        with:
          name: tb-nightly
          path: wheels
      - name: Install Twine
        run: pip install twine
      - name: Publish the package
        run: |
          twine check tb_nightly*.whl
          twine upload tb_nightly*.whl
        working-directory: wheels
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.NIGHTLY_PYPI_PASSWORD }}
